package com.oryam.howto.persistence.jpa.model;
// Generated 13 juin 2017 16:14:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

import com.oryam.howto.persistence.jpa.meta.ItemWithSeqJpaMeta;

/**
 * ItemWithSeqJpa generated by hbm2java
 */
@Entity
@Table(name = ItemWithSeqJpaMeta.TABLE)
public class ItemWithSeqJpa implements java.io.Serializable {

    private ItemWithSeqJpaId id;

    public ItemWithSeqJpa() {
        this.id = new ItemWithSeqJpaId();
    }

    @EmbeddedId
    @GeneratedValue(generator = "assigned-sequence", strategy = GenerationType.SEQUENCE)
    @GenericGenerator(
        name = "assigned-sequence",
        strategy = "com.oryam.howto.persistence.jpa.model.ItemWithSeqJpaSequenceGeneratorId",
        parameters =
    {
      @org.hibernate.annotations.Parameter(name = SequenceStyleGenerator.SEQUENCE_PARAM, value = ItemWithSeqJpaSequenceGeneratorId.SEQUENCE_NAME),
      @org.hibernate.annotations.Parameter(name = ItemWithSeqJpaSequenceGeneratorId.SEQUENCE_PREFIX, value = ItemWithSeqJpaSequenceGeneratorId.SEQUENCE_PREFIX_VALUE),
    })
    public ItemWithSeqJpaId getId() {
        return id;
    }

    public void setId(ItemWithSeqJpaId id) {
        this.id = id;
    }

}
