package com.oryam.howto.persistence.jpa.model;

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserJpa generated by hbm2java
 */
@Entity
@Table(name = "T_USER_APP", uniqueConstraints = @UniqueConstraint(columnNames = "USER_LOGIN"))
public class UserJpa implements java.io.Serializable {

    private static final long serialVersionUID = -3526318035872930190L;

    private Long userId;
    private String userLogin;
    private String userFname;
    private String userLname;
    private Integer userProfile;
    private String userComment;
    private boolean active;
    private long updateUser;
    private Date updateDate;

    public UserJpa() {
    }

    public UserJpa(String userLogin, String userFname, String userLname, Integer userProfile, boolean active, long updateUser, Date updateDate) {
        this.userLogin = userLogin;
        this.userFname = userFname;
        this.userLname = userLname;
        this.userProfile = userProfile;
        this.active = active;
        this.updateUser = updateUser;
        this.updateDate = updateDate;
    }

    public UserJpa(String userLogin, String userFname, String userLname, Integer userProfile, String userComment, boolean active, long updateUser, Date updateDate) {
        this.userLogin = userLogin;
        this.userFname = userFname;
        this.userLname = userLname;
        this.userProfile = userProfile;
        this.userComment = userComment;
        this.active = active;
        this.updateUser = updateUser;
        this.updateDate = updateDate;
    }

    @SequenceGenerator(name = "com.oryam.howto.persistence.jpa.model.UserJpaIdGenerator", sequenceName = "S_USER_ID")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "com.oryam.howto.persistence.jpa.model.UserJpaIdGenerator")

    @Column(name = "USER_ID", unique = true, nullable = false, precision = 12, scale = 0)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "USER_LOGIN", unique = true, nullable = false, length = 7)
    public String getUserLogin() {
        return this.userLogin;
    }

    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }

    @Column(name = "USER_FNAME", nullable = false, length = 100)
    public String getUserFname() {
        return this.userFname;
    }

    public void setUserFname(String userFname) {
        this.userFname = userFname;
    }

    @Column(name = "USER_LNAME", nullable = false, length = 100)
    public String getUserLname() {
        return this.userLname;
    }

    public void setUserLname(String userLname) {
        this.userLname = userLname;
    }

    @Column(name = "USER_PROFILE", nullable = false, precision = 2, scale = 0)
    public Integer getUserProfile() {
        return this.userProfile;
    }

    public void setUserProfile(Integer userProfile) {
        this.userProfile = userProfile;
    }

    @Column(name = "ACTIVE", nullable = false, precision = 1, scale = 0)
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

}
